spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME:localhost}:8761/eureka
