spring:
  application:
    name: api-user-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

  datasource:
    url: jdbc:postgresql://${DATABASE_SERVER_HOSTNAME:localhost}:5432/gymtracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8083

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME:localhost}:8761/eureka

jwt:
  secret: sM1eVxXeO3GZj2js87+V1QI0l6ZnN2Q7Wj5aQ7hjOo8=
  expiration: 3600000